# Generated by Django 5.2.6 on 2025-09-11 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleitem',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scheduleitem',
            name='start',
            field=models.DateTimeField(),
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
