# Generated by Django 5.2.6 on 2025-09-18 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_scheduleitem_end_alter_scheduleitem_start_and_more'),
        ('quarries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodServiceWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('FOODTRUCK', 'Foodtruck'), ('LUNCH', 'Mittagessen'), ('DINNER', 'Abendessen'), ('BREAKFAST', 'Frühstück'), ('SNACK', 'Snack')], default='FOODTRUCK', max_length=20)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_windows', to='events.event')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=50)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='events.event')),
                ('quarry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slots', to='quarries.quarry')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
