# Generated by Django 5.2.6 on 2025-12-16 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_foodservicewindow_scheduleslot'),
        ('quarries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['start', 'group']},
        ),
        migrations.AddField(
            model_name='scheduleslot',
            name='kind',
            field=models.CharField(choices=[('DRIVING', 'Fahren'), ('BREAK', 'Pause')], default='DRIVING', max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleslot',
            name='quarry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='quarries.quarry'),
        ),
    ]
