# Generated by Django 5.2.6 on 2025-09-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_alter_scheduleitem_end_alter_scheduleitem_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('ATTENDEE', 'Teilnehmer'), ('GUIDE', 'Guide'), ('HELPER', 'Helfer'), ('SPONSOR', 'Sponsor')], default='ATTENDEE', max_length=12)),
                ('status', models.CharField(choices=[('GOING', 'Zusage'), ('WAITLISTED', 'Warteliste'), ('NOT_GOING', 'Absage'), ('CANCELLED', 'Storniert')], default='GOING', max_length=12)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'role', 'status'), name='uniq_event_email')],
            },
        ),
    ]
