# Generated by Django 5.2.6 on 2025-12-08 20:58

import django.db.models.deletion
import registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiverTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='event-waiver')),
                ('version', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('slug', 'version')},
            },
        ),
        migrations.CreateModel(
            name='WaiverAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('device_id', models.UUIDField(default=registrations.models._default_device_id, editable=False)),
                ('content_hash', models.CharField(editable=False, max_length=64)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='waivers/')),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='waiver', to='registrations.registration')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acceptances', to='registrations.waivertemplate')),
            ],
            options={
                'ordering': ['-accepted_at'],
            },
        ),
    ]
