# Generated by Django 5.2.6 on 2025-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_foodservicewindow_scheduleslot'),
        ('registrations', '0002_waivertemplate_waiveracceptance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='registration',
            name='uniq_event_email',
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'role', 'status'], name='registratio_event_i_18401d_idx'),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['event', 'created_at'], name='registratio_event_i_f44d95_idx'),
        ),
    ]
